server:
  http2:
    enabled: true
  port: 8000
  error:
    whitelabel:
      enabled: true

spring:
  application:
    name: "@project.name@"
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    add-properties: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    rest:
      detection-strategy: annotated
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      encoding: UTF-8
  redis:
    host: us1-guiding-dragon-38410.upstash.io
    port: 38410
    username: default
    password: 6b8d3f57389c4e83a2077328ed004cdf
    ssl: false
  cache:
    type: redis

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

#resolved:
#  cache:
#    enabled: true
#    ttl: 60

app:
  detran-driver-license:
    url: http://localhost:8010
  motor-company-automobile:
    url: http://localhost:8020
  rental-company-booking:
    url: http://localhost:8030
  rental-company-contract:
    url: http://localhost:8040
  rental-company-support:
    url: http://localhost:8050
  security-company-contract:
    url: http://localhost:8060
  security-company-insurance:
    url: http://localhost:8070